FROM agrigorev/zoomcamp-model:mlops-2024-3.10.13-slim

# Set the working directory
WORKDIR /04-deployment

# Copy your script into the container
COPY starter.py .

# Set the default command to run the script
ENTRYPOINT ["python", "starter.py"]
